language: node_js
node_js:
  - "11.10.0"
cache:
  - npm
before_script:
  - npm ci
script:
  - npm run lint
  - npm run test
  - npm run build
  - now -e BOT_TOKEN=$BOT_TOKEN
  - now alias --token=$SECRET_KEY -V 2 NodeLabs-$TRAVIS_BRANCH