language: node_js
node_js:
  - "10"
before_script:
  - npm ci
script:
  - npm run lint
  - npm run test
  - npm run build
  - now --token=$SECRET_KEY
  - now alias --token=$SECRET_KEY NodeLabs-$TRAVIS_BRANCH.now.sh