language: node_js
node_js:
  - "10"
before_script:
  - npm ci
script:
  - npm run lint
  - npm run test
  - npm run build
  - npm run deploy
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"